/**
 * Download Google Fonts sebagai file lokal (self-host) + generate src/styles/fonts.css.
 *
 * Font yang diunduh (subset latin + latin-ext saja):
 *  - Plus Jakarta Sans variable (wght 200..800)
 *  - Inter variable (wght 100..900)
 *  - Space Grotesk variable (wght 300..700)
 *  - Material Symbols Outlined variable (opsz 24, wght 400, FILL 0..1, GRAD 0)
 *    -> FILL variable agar class .fill-1 (sidebar admin aktif) tetap berfungsi.
 *
 * Usage: node scripts/download-fonts.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'static', 'fonts');
mkdirSync(outDir, { recursive: true });

const UA =
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

async function fetchText(url) {
	const res = await fetch(url, { headers: { 'User-Agent': UA } });
	if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
	return res.text();
}

async function download(url, filename) {
	const res = await fetch(url, { headers: { 'User-Agent': UA } });
	if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
	const buf = Buffer.from(await res.arrayBuffer());
	writeFileSync(join(outDir, filename), buf);
	console.log(`${(buf.length / 1024).toFixed(1).padStart(8)}KB  ${filename}`);
	return buf.length;
}

// --- 1. Font teks variable (latin + latin-ext) ---
const textCssUrl =
	'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@200..800&family=Inter:wght@100..900&family=Space+Grotesk:wght@300..700&display=swap';
const textCss = await fetchText(textCssUrl);

const slug = { 'Plus Jakarta Sans': 'plus-jakarta-sans', Inter: 'inter', 'Space Grotesk': 'space-grotesk' };
const blocks = [...textCss.matchAll(/(?:\/\* ([a-z-]+) \*\/\s*)?@font-face \{([^}]+)\}/g)];

const faces = [];
const seen = new Set();
let total = 0;

for (const b of blocks) {
	const subset = b[1] || 'fallback';
	if (subset !== 'latin' && subset !== 'latin-ext') continue;
	const body = b[2];
	const family = (body.match(/font-family: '([^']+)'/) || [])[1];
	const weight = (body.match(/font-weight: ([^;]+);/) || [])[1].trim();
	const range = (body.match(/unicode-range: ([^;]+);/) || [])[1].trim();
	const url = (body.match(/url\((https:[^)]+)\)/) || [])[1];
	if (!family || !url || seen.has(url)) continue;
	seen.add(url);

	const filename = `${slug[family]}-variable-${subset}.woff2`;
	total += await download(url, filename);
	faces.push({ family, weight, filename, range, display: 'swap' });
}

// --- 2. Material Symbols Outlined variable (FILL 0..1, opsz 24, wght 400) ---
const symbolsCss = await fetchText(
	'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0..1,0&display=block'
);
const symbolsUrl = (symbolsCss.match(/url\((https:[^)]+)\)/) || [])[1];
if (!symbolsUrl) throw new Error('Material Symbols URL not found');
total += await download(symbolsUrl, 'material-symbols-outlined-fill-variable.woff2');

console.log(`TOTAL: ${(total / 1024).toFixed(1)}KB, files: ${seen.size + 1}`);

// --- 3. Generate src/styles/fonts.css ---
const cssOut = join(root, 'src', 'styles', 'fonts.css');
let css = `/* Self-hosted fonts — generated by scripts/download-fonts.mjs. Do not edit by hand. */\n`;
for (const f of faces) {
	css += `\n@font-face {\n  font-family: '${f.family}';\n  font-style: normal;\n  font-weight: ${f.weight};\n  font-display: ${f.display};\n  src: url('/fonts/${f.filename}') format('woff2');\n  unicode-range: ${f.range};\n}\n`;
}
css += `\n@font-face {\n  font-family: 'Material Symbols Outlined';\n  font-style: normal;\n  font-weight: 400;\n  font-display: block;\n  src: url('/fonts/material-symbols-outlined-fill-variable.woff2') format('woff2');\n}\n`;
writeFileSync(cssOut, css);
console.log('wrote src/styles/fonts.css');
